---
driver:
  forward_agent: yes
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: windows_2012r2-chef11
    driver_config:
      box: win2k12r2
      box_url: #insert your boxfile url here   
      gui: true
    provisioner:
      require_chef_omnibus: 11.16.4
  - name: windows_2012r2-chef12
    driver_config:
      box: win2k12r2
      box_url: #insert your boxfile url here  
      gui: true
    provisioner:
      require_chef_omnibus: 12.1.0

suites:
  - name: default
    run_list:
      - recipe[iis::default]

