name             'iis'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures Windows IIS'
source_url       'https://github.com/sous-chefs/iis'
issues_url       'https://github.com/sous-chefs/iis/issues'
chef_version     '>= 15.3'
version          '8.0.0'

supports 'windows'
