name 'iis'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'Apache-2.0'
description 'Installs/Configures Microsoft Internet Information Services'
version '7.3.0'
supports 'windows'
depends 'windows', '>= 4.1.0'
source_url 'https://github.com/chef-cookbooks/iis'
issues_url 'https://github.com/chef-cookbooks/iis/issues'
chef_version '>= 12.14'
