---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    with:
      platform: windows-latest
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: windows-latest
    strategy:
      matrix:
        instance:
          - default-windows-latest
          - disable-default-windows-latest
          - app-windows-latest
          - config-property-windows-latest
          - manager-windows-latest
          - manager-permission-windows-latest
          - module-windows-latest
          - pool-windows-latest
          - root-windows-latest
          - section-windows-latest
          - site-windows-latest
          - vdir-windows-latest
          - default-powershell-windows-latest
          - site-powershell-windows-latest
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Cinc Workstation
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Run Test Kitchen
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.yml
        run: chef exec kitchen test ${{ matrix.instance }} --destroy=always
